# Generated by Django 5.2.7 on 2025-12-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
