# Generated by Django 4.2 on 2025-11-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0002_region_delete_regions_destinations_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='region',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='website',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='sightseeing.location'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nearest_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_hotels', to='sightseeing.destinations'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='sightseeing.location'),
        ),
    ]
