# Generated by Django 4.2 on 2025-12-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0002_alter_trip_price_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='image_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('restaurant_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='sightseeing.location')),
            ],
        ),
    ]
