# Generated by Django 4.2 on 2025-12-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0002_alter_trip_price_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='image_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
