# Generated by Django 4.2 on 2025-11-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0002_region_delete_regions_destinations_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='regionName',
            new_name='locationName',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='region',
            new_name='location',
        ),
    ]
