# Generated by Django 4.2 on 2025-11-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0003_hotel_location_remove_destinations_opening_hours_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='destinations',
            unique_together={('desName', 'location')},
        ),
    ]
