# Generated by Django 4.2 on 2025-12-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0003_destinations_image_urls_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripitem',
            options={'ordering': ['day_number', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='item_type',
            field=models.CharField(choices=[('destination', 'Destination'), ('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('activity', 'Activity')], default='destination', max_length=20),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sightseeing.restaurant'),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sightseeing.trip'),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='day',
        ),
    ]
