# Generated by Django 4.2 on 2025-11-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0004_remove_destinations_opening_hours_and_more'),
    ]

    operations = [
    ]
