# Generated by Django 4.2 on 2025-12-15 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sightseeing', '0004_alter_tripitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripitem',
            options={},
        ),
        migrations.AddField(
            model_name='tripitem',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together={('user', 'destination', 'hotel')},
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripitem',
            name='updated_at',
        ),
    ]
