# Generated by Django 4.2 on 2025-11-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0005_remove_destinations_opening_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('destination_id', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='destinations',
            name='destination_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='custom_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
