# Generated by Django 4.2 on 2025-12-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0003_add_itinerary_fields'),
        ('sightseeing', '0005_alter_tripitem_options_tripitem_day_and_more'),
    ]

    operations = [
    ]
