# Generated by Django 4.2 on 2025-11-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0006_searchhistory_remove_destinations_opening_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='website',
        ),
    ]
