# Generated by Django 4.2 on 2025-12-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0007_alter_tripitem_options_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='favourite_destination_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
