# Generated by Django 4.2 on 2025-12-17 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sightseeing', '0008_usersprofile_favourite_destination_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sightseeing.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together={('user', 'trip', 'destination', 'hotel')},
        ),
    ]
