# Generated by Django 4.2 on 2025-11-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='rating',
            new_name='score',
        ),
    ]
