# Generated by Django 4.2 on 2025-11-26 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sightseeing', '0011_trip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tripitem',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sightseeing.hotel'),
        ),
        migrations.AlterField(
            model_name='tripitem',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sightseeing.destinations'),
        ),
        migrations.AlterUniqueTogether(
            name='tripitem',
            unique_together={('user', 'destination', 'hotel')},
        ),
    ]
