# Generated by Django 4.2 on 2025-11-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0012_alter_tripitem_unique_together_tripitem_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitem',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
